package com.projeto.SIARRE.enumClass;

public enum Education {
  NAO_DEFINIDA_SEM_ALFABETIZACAO,
  NAO_DEFINIDA_COM_ALFABETIZACAO,
  FUNDAMENTAL_INCOMPLETO,
  FUNDAMENTAL_COMPLETO,
  MEDIO_INCOMPLETO,
  MEDIO_COMPLETO,
  SUPERIOR_INCOMPLETO,
  SUPERIOR_COMPLETO,
  POS_GRADUACAO_INCOMPLETA,
  POS_GRADUACAO_COMPETA,
  PREFIRO_NAO_INFORMAR,
  OUTRO;
}
